### ISSUE TITLE
Can't Render to Portrait orientation for LKG Portrait

### ISSUE THREAD

**Issue by joemagiv** [Looking-Glass/blenderLKG#37]
Unless there's something I'm missing there's no way to render a portrait oriented image. My renders from blender into my LKG Portrait all come out in landscape and any attempt to put them into portrait mode distorts the image.
This issue does not reproduce with Send Quilt which works fine but there does not appear to be a way to save that quilt.

**Comment by alxdncn** [comment]
We're going to be fixing this in version 3.1 in two ways.

1. Fix the default resolution of rendered views - set them to 420 by 560
2. Enable saving a quilt out to png

**Comment by GottfriedHofmann** [comment]
Fix by https://github.com/Looking-Glass/blenderLKG/commit/2fc6b0df4ccf99546da78b0ee7521030ffe99e74 - rendering to 420 by 560 for portrait mode.

**Comment by GottfriedHofmann** [comment]
Partially fixed by https://github.com/Looking-Glass/blenderLKG/commit/b32b7e87e368694854bb063ad3b11e246eba4f0c - this adds a button that allows the user to save the quilt to a Blender image datablock. The user then has to open up an image editor in Blender, select the image datablock created and save it to disk. The result should open fine in HoloPlay studio.

**Comment by alxdncn** [comment]
This should be fixed in version 3.0.1.
